[theme]
# Primary accent color for interactive elements.
primaryColor = "#EBBA19"

# Background color for the main content area.
backgroundColor = "#002b36"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#002b36"

# Color used for almost all text.
textColor = "#fff"